### ISSUE TITLE
different wallet than the localhost one, node v6 upgrade

### ISSUE THREAD

**Issue by Pascal66** [SOELexicon/burst-pool#3]
Wich it can be possible to do that in a future release.
I know that noone ask for a improvment like that, because most of pool are just copy paste without trying to understand the mechanism.
I use node v6 for some other project, I need to have a 'deported' wallet, and your big work can help.

**Comment by SOELexicon** [comment]
it might be something to update in future. but as current. everyone in the community is running v4 and v5. updating to v6 could cause these users a lot of issues because it wont be backwards compatible with node v4 and 5. this is one of the main reasons i haven't updated the node version in the pool software. 

im busy enough with ongoing projects and guaranteed upon releasing this update ill get a metric ton of direct messages with problems

if you could raise the different wallet as a seperate issue ill take a look but i believe thats due to your wallets config. or a port thats being blocked. you need to enable a few settings so your wallet can accept post requests that other members of the network are sending. i believe its off by default or configured to only local host

even with the computer on the same network your going to find issues. cause network traffic will suddenly double on your network. basically all the miners will be sending all the requests to your pool computer. then forward all them requests over the network to another computer. to send back to the pool computer to go back to the miner. whilst this is happening the wallet will also be propagating the data its receiving from the pool. im unsure if you would want that much network traffic going around which is why usually it only makes sense to run it locally on the same machine.

the key thing is with pools is timing. if your a second off and your deadline doesnt get propagated. you wont win the block. so the more time it takes for the pool to propagate and confirm deadlines. the more your pool could and will miss in regards to winning block

**Comment by guelz** [comment]
If you're running the wallet on an different machine then the pool you need to enable API  access from the pool "machine"!
create a file in <wallet>/config called "nxt.properties" and add following two enteries:

`# Hosts from which to allow http/json API requests, if enabled.`
`nxt.allowedBotHosts=127.0.0.1; localhost; [0:0:0:0:0:0:0:1];`

and

`# Host interface on which to listen for http/json API request, default localhost only.` 
`#Set to 0.0.0.0 to allow the API server to accept requests from all network interfaces.`
`nxt.apiServerHost=127.0.0.1`

add your IP.
"nxt.properties"  overwrites "nxt-default.properties"

if "nxt.apiServerHost=" is needed for the pool I dont know and have not tried. But if your running your Wallet and pool on an headless machine like me its handy to add another IP on both (or 0.0.0.0) to have access to the wallet with an Browser.
